### ISSUE TITLE
Revise Event Envelope

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.Fundamentals#18]
Envelope does not need to hold a sequence number per type. 

By building a replication system with configurable partitioning strategies, we can simply have a replica partitioned / structured the way we want it

**Comment by smithmx** [comment]
Need to look at the metadata again.  We need metadata for the "source" bounded context (occurred, source commit sequence number, etc) which is distinct from the "receiving" bounded context when an event is broadcast between bounded contexts.

We need a SHA to ensure that the event hasn't been changed.
