### ISSUE TITLE
Remove Area from Application Artifact Identifier

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.Fundamentals#22]

**Comment by woksin** [comment]
@einari Should it be removed entirely from the project, or just from the AAI components?

**Comment by einari** [comment]
We can completely remove it from everywhere. 
This means also in the .NET SDK configuration, which becomes a bit interesting - as there are the `.Domain('')` type of extensions - which should then go and we only need to be able to map namespaces in general. We know from the ArtifactType what type it is and can deduct the area it belongs to  from that
