### ISSUE TITLE
JSON Serialization of dictionaries with concept as key does not unwrap/unbox the concept value for the key

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.Fundamentals#63]
The resulting serialized JSON looks like: 

```
[
 {
  "key": value
 }
]
```

It should just be a JSON hash/object

**Comment by woksin** [comment]
It does for me now, must be a change that we made before

**Comment by woksin** [comment]
I hade one problem when I was doing:
```csharp
var dict = _serializer.FromJson<IDictionary<IdConcept, int>>(fileContent);
```
It did not recognize the json as a ConceptDictionary.
I'll fix that
