### ISSUE TITLE
We need a JSON Log Appender

### ISSUE THREAD

**Issue by einari** [dolittle/DotNET.Fundamentals#72]
The goal is to get a JSON output that can be made indexable in for instance InfluxDB or Elastic or similar. In order for us to do that we need to define a format that is consistent for this.

We did some work for the CBS project related to this - can be found [here](https://github.com/IFRCGo/cbs/tree/master/Source/Infrastructure/Logging).

It needs to be able to get things from the execution context - which is the real challenge as Logging is our lowest level and things have dependency to it, even the `Dolittle.Execution` - which holds all the ExecutionContext information. Therefor we need to come up with a way for it to be able to have this information available to it - implicitly, not something any called should be thinking of.

Since TenantID and CorrelationID, which are the most important ones to get are concepts of `Guid`- we can probably just use `Guid` as the type and provide callbacks during configuration of the Logger Bootstrap / EntryPoint for getting these. That means we can from a higher level provide the callbacks that will provide the values from the current execution context at any given point.

This is related to both SDK and Runtime as well as we need to set this to default in those:

- [x] Define a format
- [x] Include tenant
- [x] Include application
- [x] Include bounded context
- [x] Include correlation Id
- [x] Create appender
- [ ] Make it the default appender in C# SDK
- [ ] Make it the default appender in Runtime

**Comment by woksin** [comment]
What should we do with this, @einari ?

**Comment by einari** [comment]
Suggestion:
What we can do is let the `SetInitialExecutionContext()`return the execution context it sets. 

```csharp
public static ExecutionContext SetInitialExecutionContext([CallerFilePath] string filePath = "", [CallerLineNumber] int lineNumber = 0, [CallerMemberName] string member = "")
```

Introduce a `LoggingContext` object in the Logging project:

```csharp
    public class LoggingContext
    {
        public Guid Application { get; set; }
        public Guid BoundedContext { get; set; }
        public Guid TenantId { get; set; }
        public string Environment { get; set; }
        public Guid CorrelationId { get; set; }
    }
```

Then have a `delegate` that can provide it:

```csharp
public delegate LoggingContext GetCurrentLoggingContext();
``` 

We can then have it in the `Initialize()` method for the bootstrapper for logging:

```csharp
public static ILogAppenders Initialize(ILoggerFactory loggerFactory, GetCurrentLoggingContext getCurrentLoggingContext, Assembly entryAssembly = null)
```

From something like the SDK Host object or the ASP.NET startup, you can then do the following to put it together - the `AsyncLocal<>` is an optimization to keep from generating new `LoggingContext` objects all the time:

```csharp
    public class Host : IHost
    {
        /// <summary>
        /// Initializes a new instance of <see cref="Host"/>
        /// </summary>
        public Host(ILoggerFactory loggerFactory = null, bool skipBootProcedures=false)
        {
            _initialExecutionContext = ExecutionContextManager.SetInitialExecutionContext();
            
            if( loggerFactory == null ) loggerFactory = new LoggerFactory();
            var logAppenders = Dolittle.Logging.Bootstrap.EntryPoint.Initialize(loggerFactory, GetCurrentLoggingContext);
            var logger = new Logger(logAppenders);

            var assemblies = Dolittle.Assemblies.Bootstrap.EntryPoint.Initialize(logger);
            var typeFinder = Dolittle.Types.Bootstrap.EntryPoint.Initialize(assemblies);
            Dolittle.Resources.Configuration.Bootstrap.EntryPoint.Initialize(typeFinder);
            
            var bindings = new[] {
                new BindingBuilder(Binding.For(typeof(IAssemblies))).To(assemblies).Build(),
                new BindingBuilder(Binding.For(typeof(Logging.ILogger))).To(logger).Build(),
                new BindingBuilder(Binding.For(typeof(IHost))).To(this).Build(),
            };

            var result = Dolittle.DependencyInversion.Bootstrap.Boot.Start(assemblies, typeFinder, logger, bindings);
            Container = result.Container;

            if( !skipBootProcedures ) Bootstrapper.Start(Container);
        }

        IExecutionContextManager _executionContextManager;

        AsyncLocal<LoggingContext>  _currentLoggingContext;

        LoggingContext GetCurrentLoggingContext()
        {
            if( _currentLoggingContext.HasValue ) return _currentLoggingContext.Value;

            if( _executionContextManager == null && Container != null )
                _executionContextManager = Container.Get<IExecutionContextManager>();
            
            var executionContext = null;
            if( _executionContextManager != null ) executionContext = _executionContextManager.Current;
            else executionContext = _initialExecutionContext;

            var loggingContext = new LoggingContext {
                // Values from executionContext
            };

            _currentLoggingContext.Value = loggingContext;
            return loggingContext;
        }


        /// <inheritdoc/>
        public IContainer Container { get; }
}
```
